FROM php:8.1

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y mariadb-client libzip-dev

# Update packages and install wget
RUN apt-get update \
    && apt-get install -y \
        wget \
    && rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-install pdo_mysql && \
    docker-php-ext-install zip

ARG projectname=Loris-MRI
RUN useradd -ms /bin/bash lorisadmin \
    && mkdir -p /data/${projectname} \
    && mkdir -p /opt/${projectname}/bin/mri \
WORKDIR /opt/${projectname}/bin/mri

# Update packages and install necessary tools and libraries
RUN apt-get update \
    && apt-get install -y \
        python3 \
        python3-dev \
        python3-pip \
        default-libmysqlclient-dev \
        virtualenv \
    && rm -rf /var/lib/apt/lists/*

# Download and install MINC toolkit package
# Download a file using wget and output download progress
RUN wget -q --show-progress -O /tmp/minc-toolkit-1.0.09-20170529-Debian_9.13-x86_64.deb http://packages.bic.mni.mcgill.ca/minc-toolkit/Debian/minc-toolkit-1.0.09-20170529-Debian_9.13-x86_64.deb

# Print download file size

RUN dpkg -i /tmp/minc-toolkit-1.0.09-20170529-Debian_9.13-x86_64.deb


