FROM php:8.1

RUN apt-get update && \
    apt-get install -y mariadb-client libzip-dev

RUN docker-php-ext-install pdo_mysql && \
    docker-php-ext-install zip

# todo install loris-mri here

# Set environment variables to avoid interactive prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Update the package list and install build-essential, checkinstall, and cmake
RUN apt-get update && \
    apt-get install -y build-essential checkinstall cmake

# Install Perl and CPAN
RUN apt-get install -y perl && \
    apt-get install -y libterm-readline-gnu-perl && \
    apt-get install -y perl-doc && \
    apt-get install -y libssl-dev && \
    apt-get install -y liblwp-protocol-https-perl && \
    cpan CPAN

# Reload CPAN to update metadata
RUN cpan reload cpan

# Now you can install CPAN modules or use CPAN commands

# Install any necessary dependencies specific to your application

# Set up directories and permissions as needed
ARG projectname=Loris-MRI
RUN useradd -ms /bin/bash lorisadmin \
    && mkdir -p /data/${projectname} \
    && mkdir -p /opt/${projectname}/bin/mri \

# Set the working directory
WORKDIR /opt/${projectname}/bin/mri

# Copy all files and folders from root into /opt/$projectname/bin/mri
COPY /* ./
