FROM php:8.1

# TODO: What is this variable used for ? Is it really needed ?
ENV DEBIAN_FRONTEND=noninteractive


#####################
# Install LORIS-MRI #
#####################

WORKDIR /opt/Loris-mri/bin/mri

RUN cd ..
RUN ls -alt
# Copy test files into the container
COPY ../. /opt/Loris-mri/bin/mri

RUN ls -alt


