name: LORIS Test Suite

on:
  - push
  - pull_request


jobs:
  buildjs:
    env:
      EEG_VIS_ENABLED: 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install EEG package dependencies
        run: |
          sudo apt install -y imagemagick-6-common libmagickcore-6.q16-6 libmagickwand-6.q16-6 \
             libprotobuf-dev libprotobuf23 libprotoc23 protobuf-compiler
          cd Loris/modules/electrophysiology_browser/jsx/react-series-data-viewer/
          protoc protocol-buffers/chunk.proto --js_out=import_style=commonjs,binary:./src/

      - name: Install npm modules
        run: |
          cd Loris
          npm ci

      - name: Compile LORIS javascript
        run: |
          cd Loris
          npm run compile

      - name: Create LORIS JS tarball
        run: |
          cd Loris
          tar cfvz lorisjs.tar.gz htdocs/js/components/ modules/*/js/*

      - name: Create node_modules tarball
        run: |
          cd Loris
          tar cfvz node_modules.tar.gz node_modules

      - uses: actions/upload-artifact@v3
        name: Upload node_modules artifact
        with:
          name: node_modules
          path: Loris/node_modules.tar.gz

      - uses: actions/upload-artifact@v3
        name: Upload lorisjs.tar.gz artifact
        with:
          name: lorisjs
          path: Loris/lorisjs.tar.gz

